mysql:
  host: "127.0.0.1"
  port: 3306
  database: "minecraft"
  username: "mc"
  password: "mcpassword"
  useSSL: false
  pool:
    maxPoolSize: 10
  tableName: "virtual_item_balances"
item:
  material: "DIAMOND"
  name: ""
  lore: []
  customModelData: -1
  matchEnchants: false
messages:
  prefix: "&b[Vault]&r "
  noItem: "&cYou don't have enough."
  deposited: "&aDeposited &e%amount%&a."
  withdrew: "&aWithdrew &e%amount%&a."
  balance: "&aYou have &e%amount%&a stored."
  notNumber: "&cPlease enter a number or 'all'."
  notEnoughStored: "&cYou don't have that many stored."
  inventoryFull: "&eYour inventory is full. %leftover% items not withdrawn."
